/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SalaryAnalyzerRouteImport } from './routes/salary-analyzer'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as InterviewPrepRouteImport } from './routes/interview-prep'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as CoverLetterRouteImport } from './routes/cover-letter'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AtsCheckerRouteImport } from './routes/ats-checker'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadCvRouteImport } from './routes/api/upload-cv'
import { Route as ApiParseCvTextRouteImport } from './routes/api/parse-cv-text'
import { Route as ApiGenerateResumeRouteImport } from './routes/api/generate-resume'
import { Route as ApiGenerateCoverLetterRouteImport } from './routes/api/generate-cover-letter'
import { Route as ApiAnalyzeAtsRouteImport } from './routes/api/analyze-ats'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryAnalyzerRoute = SalaryAnalyzerRouteImport.update({
  id: '/salary-analyzer',
  path: '/salary-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewPrepRoute = InterviewPrepRouteImport.update({
  id: '/interview-prep',
  path: '/interview-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLetterRoute = CoverLetterRouteImport.update({
  id: '/cover-letter',
  path: '/cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsCheckerRoute = AtsCheckerRouteImport.update({
  id: '/ats-checker',
  path: '/ats-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadCvRoute = ApiUploadCvRouteImport.update({
  id: '/api/upload-cv',
  path: '/api/upload-cv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseCvTextRoute = ApiParseCvTextRouteImport.update({
  id: '/api/parse-cv-text',
  path: '/api/parse-cv-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateResumeRoute = ApiGenerateResumeRouteImport.update({
  id: '/api/generate-resume',
  path: '/api/generate-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateCoverLetterRoute = ApiGenerateCoverLetterRouteImport.update({
  id: '/api/generate-cover-letter',
  path: '/api/generate-cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeAtsRoute = ApiAnalyzeAtsRouteImport.update({
  id: '/api/analyze-ats',
  path: '/api/analyze-ats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ats-checker': typeof AtsCheckerRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/cover-letter': typeof CoverLetterRoute
  '/examples': typeof ExamplesRoute
  '/interview-prep': typeof InterviewPrepRoute
  '/premium': typeof PremiumRoute
  '/resume': typeof ResumeRoute
  '/salary-analyzer': typeof SalaryAnalyzerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-ats': typeof ApiAnalyzeAtsRoute
  '/api/generate-cover-letter': typeof ApiGenerateCoverLetterRoute
  '/api/generate-resume': typeof ApiGenerateResumeRoute
  '/api/parse-cv-text': typeof ApiParseCvTextRoute
  '/api/upload-cv': typeof ApiUploadCvRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ats-checker': typeof AtsCheckerRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/cover-letter': typeof CoverLetterRoute
  '/examples': typeof ExamplesRoute
  '/interview-prep': typeof InterviewPrepRoute
  '/premium': typeof PremiumRoute
  '/resume': typeof ResumeRoute
  '/salary-analyzer': typeof SalaryAnalyzerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-ats': typeof ApiAnalyzeAtsRoute
  '/api/generate-cover-letter': typeof ApiGenerateCoverLetterRoute
  '/api/generate-resume': typeof ApiGenerateResumeRoute
  '/api/parse-cv-text': typeof ApiParseCvTextRoute
  '/api/upload-cv': typeof ApiUploadCvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ats-checker': typeof AtsCheckerRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/cover-letter': typeof CoverLetterRoute
  '/examples': typeof ExamplesRoute
  '/interview-prep': typeof InterviewPrepRoute
  '/premium': typeof PremiumRoute
  '/resume': typeof ResumeRoute
  '/salary-analyzer': typeof SalaryAnalyzerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-ats': typeof ApiAnalyzeAtsRoute
  '/api/generate-cover-letter': typeof ApiGenerateCoverLetterRoute
  '/api/generate-resume': typeof ApiGenerateResumeRoute
  '/api/parse-cv-text': typeof ApiParseCvTextRoute
  '/api/upload-cv': typeof ApiUploadCvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ats-checker'
    | '/blog'
    | '/contact'
    | '/cover-letter'
    | '/examples'
    | '/interview-prep'
    | '/premium'
    | '/resume'
    | '/salary-analyzer'
    | '/sitemap.xml'
    | '/api/analyze-ats'
    | '/api/generate-cover-letter'
    | '/api/generate-resume'
    | '/api/parse-cv-text'
    | '/api/upload-cv'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ats-checker'
    | '/blog'
    | '/contact'
    | '/cover-letter'
    | '/examples'
    | '/interview-prep'
    | '/premium'
    | '/resume'
    | '/salary-analyzer'
    | '/sitemap.xml'
    | '/api/analyze-ats'
    | '/api/generate-cover-letter'
    | '/api/generate-resume'
    | '/api/parse-cv-text'
    | '/api/upload-cv'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ats-checker'
    | '/blog'
    | '/contact'
    | '/cover-letter'
    | '/examples'
    | '/interview-prep'
    | '/premium'
    | '/resume'
    | '/salary-analyzer'
    | '/sitemap.xml'
    | '/api/analyze-ats'
    | '/api/generate-cover-letter'
    | '/api/generate-resume'
    | '/api/parse-cv-text'
    | '/api/upload-cv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AtsCheckerRoute: typeof AtsCheckerRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  CoverLetterRoute: typeof CoverLetterRoute
  ExamplesRoute: typeof ExamplesRoute
  InterviewPrepRoute: typeof InterviewPrepRoute
  PremiumRoute: typeof PremiumRoute
  ResumeRoute: typeof ResumeRoute
  SalaryAnalyzerRoute: typeof SalaryAnalyzerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAnalyzeAtsRoute: typeof ApiAnalyzeAtsRoute
  ApiGenerateCoverLetterRoute: typeof ApiGenerateCoverLetterRoute
  ApiGenerateResumeRoute: typeof ApiGenerateResumeRoute
  ApiParseCvTextRoute: typeof ApiParseCvTextRoute
  ApiUploadCvRoute: typeof ApiUploadCvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-analyzer': {
      id: '/salary-analyzer'
      path: '/salary-analyzer'
      fullPath: '/salary-analyzer'
      preLoaderRoute: typeof SalaryAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-prep': {
      id: '/interview-prep'
      path: '/interview-prep'
      fullPath: '/interview-prep'
      preLoaderRoute: typeof InterviewPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letter': {
      id: '/cover-letter'
      path: '/cover-letter'
      fullPath: '/cover-letter'
      preLoaderRoute: typeof CoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats-checker': {
      id: '/ats-checker'
      path: '/ats-checker'
      fullPath: '/ats-checker'
      preLoaderRoute: typeof AtsCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-cv': {
      id: '/api/upload-cv'
      path: '/api/upload-cv'
      fullPath: '/api/upload-cv'
      preLoaderRoute: typeof ApiUploadCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse-cv-text': {
      id: '/api/parse-cv-text'
      path: '/api/parse-cv-text'
      fullPath: '/api/parse-cv-text'
      preLoaderRoute: typeof ApiParseCvTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-resume': {
      id: '/api/generate-resume'
      path: '/api/generate-resume'
      fullPath: '/api/generate-resume'
      preLoaderRoute: typeof ApiGenerateResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-cover-letter': {
      id: '/api/generate-cover-letter'
      path: '/api/generate-cover-letter'
      fullPath: '/api/generate-cover-letter'
      preLoaderRoute: typeof ApiGenerateCoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-ats': {
      id: '/api/analyze-ats'
      path: '/api/analyze-ats'
      fullPath: '/api/analyze-ats'
      preLoaderRoute: typeof ApiAnalyzeAtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AtsCheckerRoute: AtsCheckerRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  CoverLetterRoute: CoverLetterRoute,
  ExamplesRoute: ExamplesRoute,
  InterviewPrepRoute: InterviewPrepRoute,
  PremiumRoute: PremiumRoute,
  ResumeRoute: ResumeRoute,
  SalaryAnalyzerRoute: SalaryAnalyzerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAnalyzeAtsRoute: ApiAnalyzeAtsRoute,
  ApiGenerateCoverLetterRoute: ApiGenerateCoverLetterRoute,
  ApiGenerateResumeRoute: ApiGenerateResumeRoute,
  ApiParseCvTextRoute: ApiParseCvTextRoute,
  ApiUploadCvRoute: ApiUploadCvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
