/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as CoverLetterRouteImport } from './routes/cover-letter'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadCvRouteImport } from './routes/api/upload-cv'
import { Route as ApiParseCvTextRouteImport } from './routes/api/parse-cv-text'
import { Route as ApiGenerateResumeRouteImport } from './routes/api/generate-resume'
import { Route as ApiGenerateCoverLetterRouteImport } from './routes/api/generate-cover-letter'
import { Route as ApiAnalyzeAtsRouteImport } from './routes/api/analyze-ats'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLetterRoute = CoverLetterRouteImport.update({
  id: '/cover-letter',
  path: '/cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadCvRoute = ApiUploadCvRouteImport.update({
  id: '/api/upload-cv',
  path: '/api/upload-cv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseCvTextRoute = ApiParseCvTextRouteImport.update({
  id: '/api/parse-cv-text',
  path: '/api/parse-cv-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateResumeRoute = ApiGenerateResumeRouteImport.update({
  id: '/api/generate-resume',
  path: '/api/generate-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateCoverLetterRoute = ApiGenerateCoverLetterRouteImport.update({
  id: '/api/generate-cover-letter',
  path: '/api/generate-cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeAtsRoute = ApiAnalyzeAtsRouteImport.update({
  id: '/api/analyze-ats',
  path: '/api/analyze-ats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cover-letter': typeof CoverLetterRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-ats': typeof ApiAnalyzeAtsRoute
  '/api/generate-cover-letter': typeof ApiGenerateCoverLetterRoute
  '/api/generate-resume': typeof ApiGenerateResumeRoute
  '/api/parse-cv-text': typeof ApiParseCvTextRoute
  '/api/upload-cv': typeof ApiUploadCvRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cover-letter': typeof CoverLetterRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-ats': typeof ApiAnalyzeAtsRoute
  '/api/generate-cover-letter': typeof ApiGenerateCoverLetterRoute
  '/api/generate-resume': typeof ApiGenerateResumeRoute
  '/api/parse-cv-text': typeof ApiParseCvTextRoute
  '/api/upload-cv': typeof ApiUploadCvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cover-letter': typeof CoverLetterRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-ats': typeof ApiAnalyzeAtsRoute
  '/api/generate-cover-letter': typeof ApiGenerateCoverLetterRoute
  '/api/generate-resume': typeof ApiGenerateResumeRoute
  '/api/parse-cv-text': typeof ApiParseCvTextRoute
  '/api/upload-cv': typeof ApiUploadCvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cover-letter'
    | '/resume'
    | '/sitemap.xml'
    | '/api/analyze-ats'
    | '/api/generate-cover-letter'
    | '/api/generate-resume'
    | '/api/parse-cv-text'
    | '/api/upload-cv'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cover-letter'
    | '/resume'
    | '/sitemap.xml'
    | '/api/analyze-ats'
    | '/api/generate-cover-letter'
    | '/api/generate-resume'
    | '/api/parse-cv-text'
    | '/api/upload-cv'
  id:
    | '__root__'
    | '/'
    | '/cover-letter'
    | '/resume'
    | '/sitemap.xml'
    | '/api/analyze-ats'
    | '/api/generate-cover-letter'
    | '/api/generate-resume'
    | '/api/parse-cv-text'
    | '/api/upload-cv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoverLetterRoute: typeof CoverLetterRoute
  ResumeRoute: typeof ResumeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAnalyzeAtsRoute: typeof ApiAnalyzeAtsRoute
  ApiGenerateCoverLetterRoute: typeof ApiGenerateCoverLetterRoute
  ApiGenerateResumeRoute: typeof ApiGenerateResumeRoute
  ApiParseCvTextRoute: typeof ApiParseCvTextRoute
  ApiUploadCvRoute: typeof ApiUploadCvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letter': {
      id: '/cover-letter'
      path: '/cover-letter'
      fullPath: '/cover-letter'
      preLoaderRoute: typeof CoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-cv': {
      id: '/api/upload-cv'
      path: '/api/upload-cv'
      fullPath: '/api/upload-cv'
      preLoaderRoute: typeof ApiUploadCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse-cv-text': {
      id: '/api/parse-cv-text'
      path: '/api/parse-cv-text'
      fullPath: '/api/parse-cv-text'
      preLoaderRoute: typeof ApiParseCvTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-resume': {
      id: '/api/generate-resume'
      path: '/api/generate-resume'
      fullPath: '/api/generate-resume'
      preLoaderRoute: typeof ApiGenerateResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-cover-letter': {
      id: '/api/generate-cover-letter'
      path: '/api/generate-cover-letter'
      fullPath: '/api/generate-cover-letter'
      preLoaderRoute: typeof ApiGenerateCoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-ats': {
      id: '/api/analyze-ats'
      path: '/api/analyze-ats'
      fullPath: '/api/analyze-ats'
      preLoaderRoute: typeof ApiAnalyzeAtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoverLetterRoute: CoverLetterRoute,
  ResumeRoute: ResumeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAnalyzeAtsRoute: ApiAnalyzeAtsRoute,
  ApiGenerateCoverLetterRoute: ApiGenerateCoverLetterRoute,
  ApiGenerateResumeRoute: ApiGenerateResumeRoute,
  ApiParseCvTextRoute: ApiParseCvTextRoute,
  ApiUploadCvRoute: ApiUploadCvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
